[package]
name = "fit-parser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
num_enum = "0.5.6"

[build-dependencies]
codegen = "0.1.3"
csv = "1.1.6"
